### ISSUE TITLE
Brackets in language selection

### ISSUE THREAD

**Issue by andeElliott** [UofGAnalytics/build-coursework#152]
On an M3 Mac the brackets in the language spec dont seem to work i.e.

\`\`\`{python}
print(3/4)
print(2**3)
\`\`\`

does not work, with an error "✖ Unknown language: ` python` is not registered", whereas removing the braces appears to work. I also get similar errors with r code blocks, unfortunately I cannot just remove the blocks as we need to specify the output format for the svg output which requires the blocks

**Comment by dmca-glasgow** [comment]
I can't replicated this (on my M1 Mac).  The following `.Rmd` file:

````md
```{python}
print(3/4)
print(2**3)
```
````

when run with:

```bash
rmarkdown --noPdf --noHexagons
```

In [this test project](https://github.com/UofGAnalytics/build-coursework/tree/master/fixtures/basic) produces:

![Screenshot 2024-09-12 at 16 37 10](https://github.com/user-attachments/assets/13aebebc-39eb-4aa9-ab58-72bb2a8db560)

Maybe my dependency versions are different, I have:

```bash
R --version 
R version 4.3.3 (2024-02-29) -- "Angel Food Cake"

python --version
Python 3.11.5

which python
/opt/homebrew/Caskroom/miniconda/base/bin/python

rmarkdown --version           
1.1.74
``

**Comment by andeElliott** [comment]
I wonder if this is a knitr issue - can I ask which version you are running?

**Comment by dmca-glasgow** [comment]
```bash
R -e "packageVersion('knitr')"
[1] ‘1.33’
```

**Comment by andeElliott** [comment]
that is a bit old (~3 years) - current version is 1.47

 - no idea if this is the difference - could you update on your system and we can see, I will try to downgrade from here

**Comment by dmca-glasgow** [comment]
Resolved in https://github.com/UofGAnalytics/build-coursework/commit/909eeaebb5c8ce59cae050212cc9afb0156dd5f4 and https://github.com/UofGAnalytics/build-coursework/commit/1c736be97334750126729085f66a61c3282d9795
