### ISSUE TITLE
texttt command is ignored

### ISSUE THREAD

**Issue by andeElliott** [UofGAnalytics/build-coursework#84]
The latex \texttt command is ignored and appears in the resultant html

**Comment by dmca-glasgow** [comment]
When I try:
```
$\texttt{foo\_bar}$
```
the output is:
![Screenshot 2022-04-06 at 17 08 45](https://user-images.githubusercontent.com/59647327/162019295-4631ab63-2e01-44b3-928e-9355219d0d8a.png)

Please let me know the intended vs. actual outcome.

**Comment by andeElliott** [comment]
The original Rmd looks like this:

`\texttt{read.table} or \texttt{read.csv} command.`

It should look like this:

<img width="247" alt="Screenshot 2022-04-06 at 21 33 54" src="https://user-images.githubusercontent.com/3300364/162065876-df098b7e-2bb9-4207-a02b-36b3b62263c0.png">

but I am currently getting:

<img width="470" alt="Screenshot 2022-04-06 at 21 35 18" src="https://user-images.githubusercontent.com/3300364/162066128-fc5ce5dc-d621-4bc6-851b-f1e501b73d51.png">

The above example looks right, I could wrap them all in a math env? Or pandoc suggested using a \`\`, but i dont know if this is the same?

**Comment by dmca-glasgow** [comment]
Yeah I would go with inline code, as Pandoc suggests: ``

This outputs an HTML `<span />`. I have specific CSS styling for inline code but not for inline TeX monospace fonts (this is the first time I've seen it!).

**Comment by andeElliott** [comment]
Okay makes sense, so there is one more that we will hit (\textsf) pandoc suggests [abcd]{.sans-serif}, I havent tested that yet, but I presume that would make sense?

**Comment by dmca-glasgow** [comment]
If it really is part of a Math equation then the TeX should work:
<img width="310" alt="Screenshot 2022-04-06 at 21 52 23" src="https://user-images.githubusercontent.com/59647327/162068771-fcee2502-9b5d-429e-8bb0-96fa567f5b93.png">
I would just discourage using TeX for formatting that isn't really an equation.

**Comment by andeElliott** [comment]
Okay that makes sense, I wonder if a small table of code that might be used (as it works in the current notes) and what it should be converted too would be helpful which we can all edit, just for the next person i.e. 

| Old version | Convert to |
|------------|------------|
| latex tables | markdown tables |
| texttt | \`\`| 
| etc | etc|

**Comment by dmca-glasgow** [comment]
Yeah that's a good idea, I'll create a Wiki here on Github 👍   Leave it with me

**Comment by dmca-glasgow** [comment]
https://github.com/UofGAnalytics/build-coursework/wiki/TeX-to-Markdown-conversion-chart

I've not created a GitHub Wiki before, are you able to edit this page?
