### ISSUE TITLE
Markdown figure sizing appears in the html

### ISSUE THREAD

**Issue by andeElliott** [UofGAnalytics/build-coursework#91]
When using the command:

``
![abcdef](image.png){ width=85% }
``

The width argument turns up in the html, not sure if i should be using a different syntax??

**Comment by dmca-glasgow** [comment]
This isn't valid Markdown syntax so yes, it wont work with my compiler.  

Pandoc has a lot of additional features which are not in the Markdown spec.

The reason for this is Markdown is originally written as a simple way to write content which will be converted to HTML, and HTML is purely for display, and CSS is for styling.  As HTML documents need to consider rendering on big screens to small mobile phones, it's not a good idea to mix styling with the content.

If you really do want to make the image a little smaller and have considered all screen sizes, there is a knitr way to do it:

\`\`\`{r fig.width="85%"}
knitr::include_graphics(image.png)
\`\`\`

**Comment by dmca-glasgow** [comment]
Closed in #100
